Assignment 2: BstTest.cpp File Reference
BstTest.cpp File Reference
#include <iostream>
#include "Bst.h"
Typedefs
typedef Bst< int > intBST
Functions
void Test01 (intBST test)
void Test02 ()
void Test03 ()
void Test04 (intBST &test)
void Test05 (intBST test)
void Test06 (intBST test)
void Test07 (intBST test)
void Test08 (intBST test)
void Test09 (intBST test)
void Test10 (intBST test)
void Test11 (intBST test)
void Test12 (intBST test)
int main ()
Typedef Documentation
intBST
typedef Bst<int> intBST
Definition at line 5 of file BstTest.cpp.
Function Documentation
main()
int main ()
Definition at line 20 of file BstTest.cpp.
 {
    intBST test;
     Test01(test);
     Test02();
     Test03();
     Test04(test);
     Test05(test);
     Test06(test);
     Test07(test);
     Test08(test);
     Test09(test);
     Test10(test);
     Test11(test);
     Test12(test);
     return 0;
 }
References Test01(), Test02(), Test03(), Test04(), Test05(), Test06(), Test07(), Test08(), Test09(), Test10(), Test11(), and Test12().
Test01()
void Test01 (intBST test)
Definition at line 40 of file BstTest.cpp.
 {
     cout << "=== Testing Default Constructor ===" << endl;
     if(test.IsEmpty())
     {
         cout << "Successful initialization" << endl << endl;
     }
     else
     {
         cout << "Unsuccessful initialization" << endl << endl;
     }
 }
References Bst< T >::IsEmpty().
Referenced by main().
Test02()
void Test02 ()
Definition at line 53 of file BstTest.cpp.
 {
     cout << "=== Testing Copy Constructor ===" << endl;
     intBST n1;
     n1.Insert(15);
     intBST n2(n1);
     n2.InorderTraversal();
     cout << endl << endl;
 }
References Bst< T >::InorderTraversal(), and Bst< T >::Insert().
Referenced by main().
Test03()
void Test03 ()
Definition at line 63 of file BstTest.cpp.
 {
     cout << "=== Testing Deep Copy ===" << endl;
     intBST n1;
     n1.Insert(88);
     intBST n2;
     n2 = n1;
     n2.InorderTraversal();
     cout << endl << endl;
 }
References Bst< T >::InorderTraversal(), and Bst< T >::Insert().
Referenced by main().
Test04()
void Test04 (intBST & test)
Definition at line 74 of file BstTest.cpp.
 {
     cout << "=== Testing Insert() ===" << endl;
     test.Insert(50);
     test.Insert(42);
     test.Insert(44);
     test.Insert(63);
     test.Insert(41);
     cout << "Display inserted items" << endl;
     test.InorderTraversal();
     cout << endl << endl;
     cout << "Test inserting duplicate item" << endl;
     test.Insert(44);
     cout << endl;
 }
References Bst< T >::InorderTraversal(), and Bst< T >::Insert().
Referenced by main().
Test05()
void Test05 (intBST test)
Definition at line 92 of file BstTest.cpp.
 {
     cout << "=== Testing InorderTraversal() ===" << endl;
     test.InorderTraversal();
     cout << endl << endl;
 }
References Bst< T >::InorderTraversal().
Referenced by main().
Test06()
void Test06 (intBST test)
Definition at line 99 of file BstTest.cpp.
 {
     cout << "=== Testing PostorderTraversal() ===" << endl;
     test.PostorderTraversal();
     cout << endl << endl;
 }
References Bst< T >::PostorderTraversal().
Referenced by main().
Test07()
void Test07 (intBST test)
Definition at line 106 of file BstTest.cpp.
 {
     cout << "=== Testing PreorderTraversal() ===" << endl;
     test.PreorderTraversal();
     cout << endl << endl;
 }
References Bst< T >::PreorderTraversal().
Referenced by main().
Test08()
void Test08 (intBST test)
Definition at line 113 of file BstTest.cpp.
 {
     cout << "=== Testing Search() ===" << endl;
     cout << "Test empty search" << endl;
     intBST n1;
     cout << "Search result: " << n1.Search(44) << endl << endl;
     cout << "Test non-existent search (120)" << endl;
     cout << "Search result: " << test.Search(120) << endl << endl;
     cout << "Test found search (44)" << endl;
     cout << "Search result: " << test.Search(44) << endl << endl;
 }
References Bst< T >::Search().
Referenced by main().
Test09()
void Test09 (intBST test)
Definition at line 127 of file BstTest.cpp.
 {
     cout << "=== Testing DeleteNode() ===" << endl;
     cout << "Test data" << endl;
     test.InorderTraversal();
     cout << endl << endl;
     cout << "Test empty tree" << endl;
     intBST n1;
     n1.DeleteNode(44);
     cout << endl;
     cout << "Test non-existent data (120)" << endl;
     test.DeleteNode(120);
     cout << endl;
     cout << "Test existing data (42)" << endl;
     test.DeleteNode(42);
     test.InorderTraversal();
     cout << endl << endl;
 }
References Bst< T >::DeleteNode(), and Bst< T >::InorderTraversal().
Referenced by main().
Test10()
void Test10 (intBST test)
Definition at line 149 of file BstTest.cpp.
 {
     cout << "=== Testing DeleteTree() ===" << endl;
     test.DeleteTree();
     cout << "Data: " << endl;
     test.InorderTraversal();
     cout << "IsEmpty: " << test.IsEmpty() << endl << endl;
 }
References Bst< T >::DeleteTree(), Bst< T >::InorderTraversal(), and Bst< T >::IsEmpty().
Referenced by main().
Test11()
void Test11 (intBST test)
Definition at line 159 of file BstTest.cpp.
 {
     cout << "=== Testing IsEmpty() ===" << endl;
     cout << "Test filled tree" << endl;
     cout << "IsEmpty: " << test.IsEmpty() << endl << endl;
     cout << "Test empty tree" << endl;
     intBST n1;
     cout << "IsEmpty: " << n1.IsEmpty() << endl << endl;
 }
References Bst< T >::IsEmpty().
Referenced by main().
Test12()
void Test12 (intBST test)
Definition at line 170 of file BstTest.cpp.
 {
     cout << "=== Testing TreeNodeCount() ===" << endl;
     cout << "Size: " << test.TreeNodeCount() << endl;
 }
References Bst< T >::TreeNodeCount().
Referenced by main().