Assignment 2: Date.h File Reference
Date.h File Reference
#include <iostream>
#include <string>
#include <sstream>
Classes
class Date
Functions
ostream & operator<< (ostream &os, const Date &date)
istream & operator>> (istream &input, Date &date)
Variables
const string MONTH_STRING [13] = {"NULL","January","February","March","April","May","June","July","August","September","October","November","December"}
Function Documentation
operator<<()
ostream& operator<< (ostream & os, const Date & date)
Overloaded << operator to print attributes of the Date
Parameters
os - Variable initialized to store output stream
date - Date object containing data to be printed
Returns
os - Return output stream to be printed
Definition at line 83 of file Date.cpp.
 {
     os << "Date : " << date.GetDate() << '\n';
     return os;
 }
References Date::GetDate().
operator>>()
istream& operator>> (istream & input, Date & date)
Overloaded >> operator to read attributes of a Date
Parameters
input - Variable initialized to store input stream
date - Date object whose attributes is to be set
Returns
input - Return EOF once all lines are read
Definition at line 63 of file Date.cpp.
 {
     string tempString;
     getline(input,tempString,' ');
     date.SetDate(tempString);
     istringstream iss(tempString); // takes the date and initialize it as a stream to be split
     getline(iss,tempString,'/');
     date.SetDay(stoi(tempString));
     getline(iss,tempString,'/');
     date.SetMonth(stoi(tempString));
     date.SetMonthString(stoi(tempString));
     getline(iss,tempString);
     date.SetYear(stoi(tempString));
     return input;
 }
References Date::SetDate(), Date::SetDay(), Date::SetMonth(), Date::SetMonthString(), and Date::SetYear().
Variable Documentation
MONTH_STRING
const string MONTH_STRING[13] = {"NULL","January","February","March","April","May","June","July","August","September","October","November","December"}
Array used to contain name of months in a year stored as strings. To be used to convert int month to string month.
Definition at line 21 of file Date.h.
Referenced by WindDataStore::CalculateAirTempMean(), WindDataStore::CalculateAirTempSD(), WindDataStore::CalculateSolarRadTotal(), WindDataStore::CalculateWindSpeedMean(), WindDataStore::CalculateWindSpeedSD(), Menu1(), Menu2(), Menu3(), PrintDataToFile(), and Date::SetMonthString().