Assignment 2: DateTest.cpp File Reference
DateTest.cpp File Reference
#include "Date.h"
Functions
void Test01 (Date date)
void Test02 ()
void Test03 (Date date)
void Test04 (Date date)
void Test05 (Date date)
void Test06 (Date date)
void Test07 (Date date)
int main ()
Function Documentation
main()
int main ()
Definition at line 11 of file DateTest.cpp.
 {
     Date test;
     Test01(test);
     Test02();
     Test03(test);
     Test04(test);
     Test05(test);
     Test06(test);
     Test07(test);
     return 0;
 }
References Test01(), Test02(), Test03(), Test04(), Test05(), Test06(), and Test07().
Test01()
void Test01 (Date date)
Definition at line 28 of file DateTest.cpp.
 {
     cout << "=== Testing Default Constructor ===" << endl;
     cout << date << endl;
 }
Referenced by main().
Test02()
void Test02 ()
Definition at line 34 of file DateTest.cpp.
 {
     cout << "=== Testing Initializing Constructor with attributes ===" << endl;
     Date date("18 April 2019");
     cout << date << endl;
 }
Referenced by main().
Test03()
void Test03 (Date date)
Definition at line 41 of file DateTest.cpp.
 {
     cout << "=== Testing Set & GetDate() ===" << endl;
     date.SetDate("30 June 2016");
     cout << date.GetDate() << endl << endl;
 }
References Date::GetDate(), and Date::SetDate().
Referenced by main().
Test04()
void Test04 (Date date)
Definition at line 48 of file DateTest.cpp.
 {
     cout << "=== Testing Set & GetDay() ===" << endl;
     date.SetDay(13);
     cout << date.GetDay() << endl << endl;
 }
References Date::GetDay(), and Date::SetDay().
Referenced by main().
Test05()
void Test05 (Date date)
Definition at line 55 of file DateTest.cpp.
 {
     cout << "=== Testing Set & GetMonth() ===" << endl;
     date.SetMonth(6);
     cout << date.GetMonth() << endl << endl;
 }
References Date::GetMonth(), and Date::SetMonth().
Referenced by main().
Test06()
void Test06 (Date date)
Definition at line 62 of file DateTest.cpp.
 {
     cout << "=== Testing Set & GetYear() ===" << endl;
     date.SetYear(1993);
     cout << date.GetYear() << endl << endl;
 }
References Date::GetYear(), and Date::SetYear().
Referenced by main().
Test07()
void Test07 (Date date)
Definition at line 69 of file DateTest.cpp.
 {
     cout << "=== Testing Set & GetMonthString() ===" << endl;
     date.SetMonthString(5);
     cout << date.GetMonthString() << endl << endl;
 }
References Date::GetMonthString(), and Date::SetMonthString().
Referenced by main().