Assignment 2: Date.cpp File Reference
Date.cpp File Reference
#include "Date.h"
Functions
istream & operator>> (istream &input, Date &date)
ostream & operator<< (ostream &os, const Date &date)
Function Documentation
operator<<()
ostream& operator<< (ostream & os, const Date & date)
Overloaded << operator to print attributes of the Date
Parameters
os - Variable initialized to store output stream
date - Date object containing data to be printed
Returns
os - Return output stream to be printed
Definition at line 83 of file Date.cpp.
 {
     os << "Date : " << date.GetDate() << '\n';
     return os;
 }
References Date::GetDate().
operator>>()
istream& operator>> (istream & input, Date & date)
Overloaded >> operator to read attributes of a Date
Parameters
input - Variable initialized to store input stream
date - Date object whose attributes is to be set
Returns
input - Return EOF once all lines are read
Definition at line 63 of file Date.cpp.
 {
     string tempString;
     getline(input,tempString,' ');
     date.SetDate(tempString);
     istringstream iss(tempString); // takes the date and initialize it as a stream to be split
     getline(iss,tempString,'/');
     date.SetDay(stoi(tempString));
     getline(iss,tempString,'/');
     date.SetMonth(stoi(tempString));
     date.SetMonthString(stoi(tempString));
     getline(iss,tempString);
     date.SetYear(stoi(tempString));
     return input;
 }
References Date::SetDate(), Date::SetDay(), Date::SetMonth(), Date::SetMonthString(), and Date::SetYear().