Assignment 2: TimeTest.cpp File Reference
TimeTest.cpp File Reference
#include "Time.h"
Functions
void Test01 (Time time)
void Test02 ()
void Test03 (Time time)
int main ()
Function Documentation
main()
int main ()
Definition at line 7 of file TimeTest.cpp.
 {
     Time test;
     Test01(test);
     Test02();
     Test03(test);
     return 0;
 }
References Test01(), Test02(), and Test03().
Test01()
void Test01 (Time time)
Definition at line 18 of file TimeTest.cpp.
 {
     cout << "=== Testing Default Constructor ===" << endl;
     cout << time << endl << endl;
 }
Referenced by main().
Test02()
void Test02 ()
Definition at line 24 of file TimeTest.cpp.
 {
     cout << "=== Testing Initializing Constructor with attributes ===" << endl;
     Time time("15:00");
     cout << time << endl;
 }
Referenced by main().
Test03()
void Test03 (Time time)
Definition at line 31 of file TimeTest.cpp.
 {
     cout << "=== Testing Set & GetDate() ===" << endl;
     time.SetTime("9:00");
     cout << time.GetTime() << endl << endl;
 }
References Time::GetTime(), and Time::SetTime().
Referenced by main().