Assignment 2: WindData.cpp File Reference
WindData.cpp File Reference
#include "WindData.h"
Functions
ostream & operator<< (ostream &os, const WindData &wd)
Function Documentation
operator<<()
ostream& operator<< (ostream & os, const WindData & wd)
Overloaded >> operator to read attributes of a WindData
Parameters
input - Variable initialized to store input stream
wd - WindData object whose attributes is to be set
Returns
input - Return EOF once all lines are read
Definition at line 78 of file WindData.cpp.
 {
     Date d;
     wd.GetDate(d);
     Time t;
     wd.GetTime(t);
     os << d;
     os << t;
     os << "Speed           : " << wd.GetSpeed() << endl;
     os << "Air Temperature : " << wd.GetAirTemp() << endl;
     os << "Solar Radiation : " << wd.GetSolarRad() << endl;
     return os;
 }
References WindData::GetAirTemp(), WindData::GetDate(), WindData::GetSolarRad(), WindData::GetSpeed(), and WindData::GetTime().