Assignment 2: WindDataTest.cpp File Reference
WindDataTest.cpp File Reference
#include "WindData.h"
#include <iostream>
Functions
void Test01 (WindData test)
void Test02 ()
void Test03 (WindData test)
void Test04 (WindData test)
void Test05 (WindData test)
void Test06 (WindData test)
void Test07 (WindData test)
void Test08 (WindData test)
int main ()
Function Documentation
main()
int main ()
Definition at line 13 of file WindDataTest.cpp.
 {
     WindData test;
     Test01(test);
     Test02();
     Test03(test);
     Test04(test);
     Test05(test);
     Test06(test);
     Test07(test);
     Test08(test);
     return 0;
 }
References Test01(), Test02(), Test03(), Test04(), Test05(), Test06(), Test07(), and Test08().
Test01()
void Test01 (WindData test)
Definition at line 29 of file WindDataTest.cpp.
 {
     cout << "=== Testing Default Constructor ===" << endl;
     cout << test << endl;
 }
Referenced by main().
Test02()
void Test02 ()
Definition at line 35 of file WindDataTest.cpp.
 {
     cout << "=== Testing Initialized Constructor ===" << endl;
     Date d("24 June 1993");
     Time t("8:34");
     WindData temp(d,t,12.34,45.67,65);
     cout << temp << endl;
 }
Referenced by main().
Test03()
void Test03 (WindData test)
Definition at line 44 of file WindDataTest.cpp.
 {
     cout << "=== Testing Set & Get Date ===" << endl;
     Date d("13 April 2003");
     test.SetDate(d);
     Date anotherD;
     test.GetDate(anotherD);
     cout << anotherD << endl;
 }
References WindData::GetDate(), and WindData::SetDate().
Referenced by main().
Test04()
void Test04 (WindData test)
Definition at line 54 of file WindDataTest.cpp.
 {
     cout << "=== Testing Set & Get Time ===" << endl;
     Time t("12:45");
     test.SetTime(t);
     Time anotherT;
     test.GetTime(anotherT);
     cout << anotherT << endl;
 }
References WindData::GetTime(), and WindData::SetTime().
Referenced by main().
Test05()
void Test05 (WindData test)
Definition at line 64 of file WindDataTest.cpp.
 {
     cout << "=== Testing Set & Get Speed ===" << endl;
     test.SetSpeed(45.45);
     cout << test.GetSpeed() << endl << endl;
 }
References WindData::GetSpeed(), and WindData::SetSpeed().
Referenced by main().
Test06()
void Test06 (WindData test)
Definition at line 71 of file WindDataTest.cpp.
 {
     cout << "=== Testing Set & Get AirTemp ===" << endl;
     test.SetAirTemp(95.51);
     cout << test.GetAirTemp() << endl << endl;
 }
References WindData::GetAirTemp(), and WindData::SetAirTemp().
Referenced by main().
Test07()
void Test07 (WindData test)
Definition at line 78 of file WindDataTest.cpp.
 {
     cout << "=== Testing Set & Get SolarRad ===" << endl;
     test.SetSolarRad(510);
     cout << test.GetSolarRad() << endl << endl;
 }
References WindData::GetSolarRad(), and WindData::SetSolarRad().
Referenced by main().
Test08()
void Test08 (WindData test)
Definition at line 85 of file WindDataTest.cpp.
 {
     cout << "=== Testing SolarRad Minimum Condition (<=100) ===" << endl;
     test.SetSolarRad(50);
     cout << test.GetSolarRad() << endl << endl;
 }
References WindData::GetSolarRad(), and WindData::SetSolarRad().
Referenced by main().