Assignment 2: WindData Class Reference
WindData Class Reference
#include <WindData.h>
Public Member Functions
WindData ()
WindData (Date date, Time time, float speed, float airTemp, int solarRad)
void GetDate (Date &date) const
void GetTime (Time &time) const
float GetSpeed () const
float GetAirTemp () const
int GetSolarRad () const
void SetDate (const Date &date)
void SetTime (const Time &time)
void SetSpeed (float speed)
void SetAirTemp (float airTemp)
void SetSolarRad (int solarRad)
bool operator== (const WindData &another)
bool operator< (const WindData &another)
bool operator> (const WindData &another)
Private Attributes
Date m_date
Time m_time
float m_speed
float m_airTemp
int m_solarRad
Detailed Description
This class is used to hold all the required wind data information
Definition at line 18 of file WindData.h.
Constructor & Destructor Documentation
WindData() [1/2]
WindData::WindData ()
Default constructor
Definition at line 3 of file WindData.cpp.
 {
     m_speed = 0;
     m_airTemp = 0;
     m_solarRad = 0;
 }
References m_airTemp, m_solarRad, and m_speed.
WindData() [2/2]
WindData::WindData (Date date, Time time, float speed, float airTemp, int solarRad)
Constructor to initialize the WindData attribute
Parameters
date - Time of wind record
time - Date of wind record
speed - Wind Speed
airTemp - Air Temperature
solarRad - Solar Radiation
Definition at line 10 of file WindData.cpp.
 {
     m_date = date;
     m_time = time;
     m_speed = speed;
     m_airTemp = airTemp;
     m_solarRad = solarRad;
 }
References m_airTemp, m_date, m_solarRad, m_speed, and m_time.
Member Function Documentation
GetAirTemp()
float WindData::GetAirTemp () const
Get air temperature
Returns
airTemp - Air temperature
Definition at line 34 of file WindData.cpp.
 {
     return m_airTemp;
 }
References m_airTemp.
Referenced by WindDataStore::GetAirTempSum(), WindDataStore::GetAirTempVector(), operator<<(), and Test06().
GetDate()
void WindData::GetDate (Date & date) const
Get date
Parameters
date - Date object to be retrieved to
Definition at line 19 of file WindData.cpp.
 {
     date = m_date;
 }
References m_date.
Referenced by WindDataStore::CalculatesPCCS_R(), WindDataStore::CalculatesPCCS_T(), WindDataStore::CalculatesPCCT_R(), WindDataStore::GetsPCCAirTempMean(), WindDataStore::GetsPCCSolarRadMean(), WindDataStore::GetsPCCWindSpeedMean(), operator<(), operator<<(), operator==(), operator>(), WindDataStore::StoreIntoMap(), Test03(), and Test07().
GetSolarRad()
int WindData::GetSolarRad () const
Get solar radiation
Returns
solarRad - Solar radiation
Definition at line 39 of file WindData.cpp.
 {
     return m_solarRad;
 }
References m_solarRad.
Referenced by WindDataStore::GetSolarRadSum(), WindDataStore::GetSolarRadVector(), operator<<(), Test07(), and Test08().
GetSpeed()
float WindData::GetSpeed () const
Get speed
Returns
speed - Speed of wind
Definition at line 29 of file WindData.cpp.
 {
     return m_speed;
 }
References m_speed.
Referenced by WindDataStore::GetWindSpeedSum(), WindDataStore::GetWindSpeedVector(), operator<<(), and Test05().
GetTime()
void WindData::GetTime (Time & time) const
Get time
Parameters
time - Date object to be retrieved to
Definition at line 24 of file WindData.cpp.
 {
     time = m_time;
 }
References m_time.
Referenced by operator<(), operator<<(), operator==(), operator>(), and Test04().
operator<()
bool WindData::operator< (const WindData & another)
Overloaded < method to compare WindData objects
Parameters
another - WindData Object to be compared with
Returns
bool - True if comparison is successful, false otherwise
Definition at line 104 of file WindData.cpp.
 {
     Date d1, d2;
     Time t1, t2;
     GetDate(d1);
     GetTime(t1);
     another.GetDate(d2);
     another.GetTime(t2);
     return ((d1.GetDate()+t1.GetTime()) < (d2.GetDate()+t2.GetTime()));
 }
References GetDate(), Date::GetDate(), Time::GetTime(), and GetTime().
operator==()
bool WindData::operator== (const WindData & another)
Overloaded == method to compare WindData objects
Parameters
another - WindData Object to be compared with
Returns
bool - True if comparison is successful, false otherwise
Definition at line 93 of file WindData.cpp.
 {
     Date d1, d2;
     Time t1, t2;
     GetDate(d1);
     GetTime(t1);
     another.GetDate(d2);
     another.GetTime(t2);
     return ((d1.GetDate()+t1.GetTime()) == (d2.GetDate()+t2.GetTime()));
 }
References GetDate(), Date::GetDate(), Time::GetTime(), and GetTime().
operator>()
bool WindData::operator> (const WindData & another)
Overloaded > method to compare WindData objects
Parameters
another - WindData Object to be compared with
Returns
bool - True if comparison is successful, false otherwise
Definition at line 115 of file WindData.cpp.
 {
     {
         Date d1, d2;
         Time t1, t2;
         GetDate(d1);
         GetTime(t1);
         another.GetDate(d2);
         another.GetTime(t2);
         return ((d1.GetDate()+t1.GetTime()) > (d2.GetDate()+t2.GetTime()));
     }
 }
References GetDate(), Date::GetDate(), Time::GetTime(), and GetTime().
SetAirTemp()
void WindData::SetAirTemp (float airTemp)
Set air temperature
Parameters
airTemp - Air temperature to be set
Definition at line 59 of file WindData.cpp.
 {
     m_airTemp = airTemp;
 }
References m_airTemp.
Referenced by WindDataStore::StoreAirTemp(), and Test06().
SetDate()
void WindData::SetDate (const Date & date)
Set date
Parameters
date - Date object to be set
Definition at line 44 of file WindData.cpp.
 {
     m_date = date;
 }
References m_date.
Referenced by WindDataStore::StoreDateAndTime(), Test03(), and Test07().
SetSolarRad()
void WindData::SetSolarRad (int solarRad)
Set solar radiation
Parameters
solarRad - Solar radiation to be set
Definition at line 64 of file WindData.cpp.
 {
     //only store solar radiation if >= 100
     if(solarRad >= 100)
     {
         m_solarRad = solarRad;
     }
     else
     {
         m_solarRad = 0;
     }
 }
References m_solarRad.
Referenced by WindDataStore::StoreSolarRad(), Test07(), and Test08().
SetSpeed()
void WindData::SetSpeed (float speed)
Set speed
Parameters
speed - Speed to be set
Definition at line 54 of file WindData.cpp.
 {
     m_speed = speed;
 }
References m_speed.
Referenced by WindDataStore::StoreSpeed(), and Test05().
SetTime()
void WindData::SetTime (const Time & time)
Set time
Parameters
time - Time object to be set
Definition at line 49 of file WindData.cpp.
 {
     m_time = time;
 }
References m_time.
Referenced by WindDataStore::StoreDateAndTime(), Test04(), and Test07().
Member Data Documentation
m_airTemp
float WindData::m_airTemp private
Air Temperature at time of record
Definition at line 39 of file WindData.h.
Referenced by GetAirTemp(), SetAirTemp(), and WindData().
m_date
Date WindData::m_date private
Date class object holding the date of wind record
Definition at line 24 of file WindData.h.
Referenced by GetDate(), SetDate(), and WindData().
m_solarRad
int WindData::m_solarRad private
Solar radiation at time of record
Definition at line 44 of file WindData.h.
Referenced by GetSolarRad(), SetSolarRad(), and WindData().
m_speed
float WindData::m_speed private
Wind speed at time of record
Definition at line 34 of file WindData.h.
Referenced by GetSpeed(), SetSpeed(), and WindData().
m_time
Time WindData::m_time private
Time class object holding the time of wind record
Definition at line 29 of file WindData.h.
Referenced by GetTime(), SetTime(), and WindData().
The documentation for this class was generated from the following files:
WindData.h
WindData.cpp