Assignment 2: WindDataStore Class Reference
WindDataStore Class Reference
#include <WindDataStore.h>
Public Member Functions
WindDataStore ()
int Size ()
void GetBst (wdBst &wdBST, itrMap it)
void GetMap (bstMap &othermap)
bool ReadInputFileToStorage (const string &fileName)
float CalculateWindSpeedMean (int month, int year)
float CalculateWindSpeedSD (int month, int year)
float CalculateAirTempMean (int month, int year)
float CalculateAirTempSD (int month, int year)
int CalculateSolarRadTotal (int month, int year)
float CalculatesPCCS_T (int month)
float CalculatesPCCS_R (int month)
float CalculatesPCCT_R (int month)
Private Member Functions
void StoreIntoMap (WindData wd)
void SetHeaderNames (string &line)
void StoreDateAndTime (WindData &wd, string &line, int currentColumn, const string &fileName)
void StoreAirTemp (WindData &wd, string &line, int currentColumn, const string &fileName)
void StoreSpeed (WindData &wd, string &line, int currentColumn, const string &fileName)
void StoreSolarRad (WindData &wd, string &line, int currentColumn, const string &fileName)
float GetsPCCWindSpeedMean (int month)
float GetsPCCAirTempMean (int month)
float GetsPCCSolarRadMean (int month)
Static Private Member Functions
static void GetWindSpeedSum (WindData &wd, float &sum)
static void GetWindSpeedVector (WindData &wd, vector< float > &wsv)
static void GetAirTempSum (WindData &wd, float &sum)
static void GetAirTempVector (WindData &wd, vector< float > &atv)
static void GetSolarRadSum (WindData &wd, int &sum)
static void GetSolarRadVector (WindData &wd, vector< int > &srv)
Private Attributes
bstMap m_bstMap
vector< string > m_headerNames
Detailed Description
This class is used to store WindData objects into multiple BSTs, which would then be stored into a map of the BSTs. The WindData is stored in BSTs, which would be stored into a map segregated according to the month and year of the record.
Definition at line 45 of file WindDataStore.h.
Constructor & Destructor Documentation
WindDataStore()
WindDataStore::WindDataStore ()
Default constructor
Definition at line 3 of file WindDataStore.cpp.
 {}
Member Function Documentation
CalculateAirTempMean()
float WindDataStore::CalculateAirTempMean (int month, int year)
This method is used to calculate the average air temperature of given month and year
Parameters
month - Month to be calculated
year - Year to be calculated
Returns
mean - Average air temperature
Definition at line 249 of file WindDataStore.cpp.
 {
     float sum;
     string key = MONTH_STRING[month]+to_string(year);
     if(m_bstMap.find(key) != m_bstMap.end())
     {
         wdBst tree = m_bstMap.at(key);
         tree.InorderTraversal(GetAirTempSum,sum);
         float mean = sum / (float)tree.TreeNodeCount();
         if(mean == 0)
         {
             return 0;
         }
         else
         {
             return mean;
         }
     }
     else
     {
         return 0;
     }
 }
References GetAirTempSum(), Bst< T >::InorderTraversal(), m_bstMap, MONTH_STRING, and Bst< T >::TreeNodeCount().
Referenced by CalculateAirTempSD(), CheckDataExistInMonth(), CheckDataExistInYear(), Menu2(), PrintDataToFile(), and Test04().
CalculateAirTempSD()
float WindDataStore::CalculateAirTempSD (int month, int year)
This method is used to calculate the standard deviation of air temperature of given month and year
Parameters
month - Month to be calculated
year - Year to be calculated
Returns
sd - Air temperature standard deviation
Definition at line 280 of file WindDataStore.cpp.
 {
     string key = MONTH_STRING[month]+to_string(year);
     vector<float> wsv;
     if(m_bstMap.find(key) != m_bstMap.end())
     {
         wdBst tree = m_bstMap.at(key);
         tree.InorderTraversal(GetAirTempVector,wsv);
         float sd;
         float mean = CalculateAirTempMean(month,year);
         for(float speed : wsv)
         {
             sd += (speed - mean)*(speed - mean);
         }
         sd = sd / wsv.size();
         sd = sqrt(sd);
         if(sd == 0)
         {
             return 0;
         }
         else
         {
             return sd;
         }
     }
     else
     {
         return 0;
     }
 }
References CalculateAirTempMean(), GetAirTempVector(), Bst< T >::InorderTraversal(), m_bstMap, and MONTH_STRING.
Referenced by Menu2(), PrintDataToFile(), and Test05().
CalculateSolarRadTotal()
int WindDataStore::CalculateSolarRadTotal (int month, int year)
This method is used to calculate the total solar radiation of given month and year
Parameters
month - Month to be calculated
year - Year to be calculated
Returns
sum - Total solar radiation
Definition at line 319 of file WindDataStore.cpp.
 {
     int sum;
     string key = MONTH_STRING[month]+to_string(year);
     if(m_bstMap.find(key) != m_bstMap.end())
     {
         wdBst tree = m_bstMap.at(key);
         tree.InorderTraversal(GetSolarRadSum,sum);
         return sum;
     }
     else
     {
         return 0;
     }
 }
References GetSolarRadSum(), Bst< T >::InorderTraversal(), m_bstMap, and MONTH_STRING.
Referenced by CheckDataExistInMonth(), CheckDataExistInYear(), PrintDataToFile(), and Test06().
CalculatesPCCS_R()
float WindDataStore::CalculatesPCCS_R (int month)
Method used to calculate the Sample Pearson Correlation Coefficient of a specified month in every year using wind speed and solar rad.
Parameters
month - Month to be calculated
Returns
sPPC - Sample Pearson Correlation Coefficient calculated
Definition at line 517 of file WindDataStore.cpp.
 {
     itrMap it = m_bstMap.begin();
     wdBst tree;
     WindData wd;
     Date d;
     //do windspeed first
     vector<float> wsVector;
     while(it != m_bstMap.end())
     {
         tree = it->second;
         tree.GetRootElement(wd);
         wd.GetDate(d);
         if(d.GetMonth() == month)
         {
             tree.InorderTraversal(GetWindSpeedVector,wsVector);
         }
         ++it;
     }
     float wsSum;
     float wsMean = GetsPCCWindSpeedMean(month);
     for(float speed : wsVector)
     {
         wsSum += (speed - wsMean) * (speed - wsMean);
     }
     //do solarrad
     it = m_bstMap.begin();
     vector<int> srVector;
     while(it != m_bstMap.end())
     {
         tree = it->second;
         tree.GetRootElement(wd);
         wd.GetDate(d);
         if(d.GetMonth() == month)
         {
             tree.InorderTraversal(GetSolarRadVector,srVector);
         }
         ++it;
     }
     float srSum;
     float srMean = GetsPCCSolarRadMean(month);
     for(float rad : srVector)
     {
         srSum += (rad - srMean) * (rad - srMean);
     }
     //find numerator
     float numerator = 0;
     for(int i = 0; i < srVector.size(); i++)
     {
         numerator += (wsVector.at(i) - wsMean) * (srVector.at(i) - srMean);
     }
     //find denominator
     float denominator = sqrt(wsSum*srSum);
     float sPCC = numerator/denominator;
     return sPCC;
 }
References WindData::GetDate(), Date::GetMonth(), Bst< T >::GetRootElement(), GetSolarRadVector(), GetsPCCSolarRadMean(), GetsPCCWindSpeedMean(), GetWindSpeedVector(), Bst< T >::InorderTraversal(), and m_bstMap.
Referenced by Menu3(), and Test10().
CalculatesPCCS_T()
float WindDataStore::CalculatesPCCS_T (int month)
Method used to calculate the Sample Pearson Correlation Coefficient of a specified month in every year using wind speed and air temp.
Parameters
month - Month to be calculated
Returns
sPPC - Sample Pearson Correlation Coefficient calculated
Definition at line 448 of file WindDataStore.cpp.
 {
     itrMap it = m_bstMap.begin();
     wdBst tree;
     WindData wd;
     Date d;
     //do windspeed first
     vector<float> wsVector;
     while(it != m_bstMap.end())
     {
         tree = it->second;
         tree.GetRootElement(wd);
         wd.GetDate(d);
         if(d.GetMonth() == month)
         {
             tree.InorderTraversal(GetWindSpeedVector,wsVector);
         }
         ++it;
     }
     float wsSum;
     float wsMean = GetsPCCWindSpeedMean(month);
     for(float speed : wsVector)
     {
         wsSum += (speed - wsMean) * (speed - wsMean);
     }
     //do airtemp
     it = m_bstMap.begin();
     vector<float> atVector;
     while(it != m_bstMap.end())
     {
         tree = it->second;
         tree.GetRootElement(wd);
         wd.GetDate(d);
         if(d.GetMonth() == month)
         {
             tree.InorderTraversal(GetAirTempVector,atVector);
         }
         ++it;
     }
     float atSum;
     float atMean = GetsPCCAirTempMean(month);
     for(float temp : atVector)
     {
         atSum += (temp - atMean) * (temp - atMean);
     }
     //find numerator
     float numerator = 0;
     for(int i = 0; i < atVector.size(); i++)
     {
         numerator += (wsVector.at(i) - wsMean) * (atVector.at(i) - atMean);
     }
     //find denominator
     float denominator = sqrt(wsSum*atSum);
     float sPCC = numerator/denominator;
     return sPCC;
 }
References GetAirTempVector(), WindData::GetDate(), Date::GetMonth(), Bst< T >::GetRootElement(), GetsPCCAirTempMean(), GetsPCCWindSpeedMean(), GetWindSpeedVector(), Bst< T >::InorderTraversal(), and m_bstMap.
Referenced by Menu3(), and Test09().
CalculatesPCCT_R()
float WindDataStore::CalculatesPCCT_R (int month)
Method used to calculate the Sample Pearson Correlation Coefficient of a specified month in every year using air temp and solar rad.
Parameters
month - Month to be calculated
Returns
sPPC - Sample Pearson Correlation Coefficient calculated
Definition at line 581 of file WindDataStore.cpp.
 {
     itrMap it = m_bstMap.begin();
     wdBst tree;
     WindData wd;
     Date d;
     //do airtemp first
     vector<float> atVector;
     while(it != m_bstMap.end())
     {
         tree = it->second;
         tree.GetRootElement(wd);
         wd.GetDate(d);
         if(d.GetMonth() == month)
         {
             tree.InorderTraversal(GetAirTempVector,atVector);
         }
         ++it;
     }
     float atSum;
     float atMean = GetsPCCAirTempMean(month);
     for(float temp : atVector)
     {
         atSum += (temp - atMean) * (temp - atMean);
     }
     //do solarrad
     it = m_bstMap.begin();
     vector<int> srVector;
     while(it != m_bstMap.end())
     {
         tree = it->second;
         tree.GetRootElement(wd);
         wd.GetDate(d);
         if(d.GetMonth() == month)
         {
             tree.InorderTraversal(GetSolarRadVector,srVector);
         }
         ++it;
     }
     float srSum;
     float srMean = GetsPCCSolarRadMean(month);
     for(float rad : srVector)
     {
         srSum += (rad - srMean) * (rad - srMean);
     }
     //find numerator
     float numerator = 0;
     for(int i = 0; i < srVector.size(); i++)
     {
         numerator += (atVector.at(i) - atMean) * (srVector.at(i) - srMean);
     }
     //find denominator
     float denominator = sqrt(atSum*srSum);
     float sPCC = numerator/denominator;
     return sPCC;
 }
References GetAirTempVector(), WindData::GetDate(), Date::GetMonth(), Bst< T >::GetRootElement(), GetSolarRadVector(), GetsPCCAirTempMean(), GetsPCCSolarRadMean(), Bst< T >::InorderTraversal(), and m_bstMap.
Referenced by Menu3(), and Test11().
CalculateWindSpeedMean()
float WindDataStore::CalculateWindSpeedMean (int month, int year)
This method is used to calculate the average wind speed of given month and year
Parameters
month - Month to be calculated
year - Year to be calculated
Returns
mean - Average wind speed
Definition at line 179 of file WindDataStore.cpp.
 {
     float sum;
     string key = MONTH_STRING[month]+to_string(year);
     if(m_bstMap.find(key) != m_bstMap.end())
     {
         wdBst tree = m_bstMap.at(key);
         tree.InorderTraversal(GetWindSpeedSum,sum);
         float mean = sum / (float)tree.TreeNodeCount();
         if(mean == 0)
         {
             return 0;
         }
         else
         {
             return mean;
         }
     }
     else
     {
         return 0;
     }
 }
References GetWindSpeedSum(), Bst< T >::InorderTraversal(), m_bstMap, MONTH_STRING, and Bst< T >::TreeNodeCount().
Referenced by CalculateWindSpeedSD(), CheckDataExistInMonth(), CheckDataExistInYear(), Menu1(), PrintDataToFile(), and Test02().
CalculateWindSpeedSD()
float WindDataStore::CalculateWindSpeedSD (int month, int year)
This method is used to calculate the standard deviation of wind speed of given month and year
Parameters
month - Month to be calculated
year - Year to be calculated
Returns
sd - Wind speed standard deviation
Definition at line 210 of file WindDataStore.cpp.
 {
     string key = MONTH_STRING[month]+to_string(year);
     vector<float> wsv;
     if(m_bstMap.find(key) != m_bstMap.end())
     {
         wdBst tree = m_bstMap.at(key);
         tree.InorderTraversal(GetWindSpeedVector,wsv);
         float sd;
         float mean = CalculateWindSpeedMean(month,year);
         for(float speed : wsv)
         {
             sd += (speed - mean)*(speed - mean);
         }
         sd = sd / wsv.size();
         sd = sqrt(sd);
         if(sd == 0)
         {
             return 0;
         }
         else
         {
             return sd;
         }
     }
     else
     {
         return 0;
     }
 }
References CalculateWindSpeedMean(), GetWindSpeedVector(), Bst< T >::InorderTraversal(), m_bstMap, and MONTH_STRING.
Referenced by Menu1(), PrintDataToFile(), and Test03().
GetAirTempSum()
void WindDataStore::GetAirTempSum (WindData & wd, float & sum) static private
Method used to get sum of air temp. To be passed into BST InorderTraversal through function passing
Parameters
wd - WindData object, will be passed in by BST InorderTraversal method
sum - Container for sum of air temp calculated.
Definition at line 275 of file WindDataStore.cpp.
 {
     sum += wd.GetAirTemp();
 }
References WindData::GetAirTemp().
Referenced by CalculateAirTempMean(), and GetsPCCAirTempMean().
GetAirTempVector()
void WindDataStore::GetAirTempVector (WindData & wd, vector< float > & atv) static private
Method used to get air temp from BST, stored into a vector<float>. To be passed into BST InorderTraversal through function passing
Parameters
wd - WindData object, will be passed in by BST InorderTraversal method
atv - Container for air temp objects to be stored
Definition at line 314 of file WindDataStore.cpp.
 {
     atv.push_back(wd.GetAirTemp());
 }
References WindData::GetAirTemp().
Referenced by CalculateAirTempSD(), CalculatesPCCS_T(), and CalculatesPCCT_R().
GetBst()
void WindDataStore::GetBst (wdBst & wdBST, itrMap it)
Method to get BST. It uses iterators for loops.
Parameters
wdBST - WindData BST to be retrieved by reference
it - Map iterator
Definition at line 19 of file WindDataStore.cpp.
 {
     wdBST = it->second;
 }
Referenced by Menu5(), and Test01().
GetMap()
void WindDataStore::GetMap (bstMap & othermap)
Method to get map
Parameters
othermap - Map to be retrieved by reference
Definition at line 24 of file WindDataStore.cpp.
 {
     othermap = m_bstMap;
 }
References m_bstMap.
Referenced by Menu5(), Test01(), Test07(), and Test08().
GetSolarRadSum()
void WindDataStore::GetSolarRadSum (WindData & wd, int & sum) static private
Method used to get sum of solar rad. To be passed into BST InorderTraversal through function passing
Parameters
wd - WindData object, will be passed in by BST InorderTraversal method
sum - Container for sum of solar rad calculated.
Definition at line 335 of file WindDataStore.cpp.
 {
     sum += wd.GetSolarRad();
 }
References WindData::GetSolarRad().
Referenced by CalculateSolarRadTotal(), and GetsPCCSolarRadMean().
GetSolarRadVector()
void WindDataStore::GetSolarRadVector (WindData & wd, vector< int > & srv) static private
Method used to get solar rad from BST, stored into a vector<int>. To be passed into BST InorderTraversal through function passing
Parameters
wd - WindData object, will be passed in by BST InorderTraversal method
srv - Container for solar rad objects to be stored
Definition at line 512 of file WindDataStore.cpp.
 {
     srv.push_back(wd.GetSolarRad());
 }
References WindData::GetSolarRad().
Referenced by CalculatesPCCS_R(), and CalculatesPCCT_R().
GetsPCCAirTempMean()
float WindDataStore::GetsPCCAirTempMean (int month) private
Method to get the mean of air temp in every for a specified month.
Parameters
month - Month to be calculated
Returns
mean - Mean of air temp
Definition at line 376 of file WindDataStore.cpp.
 {
     itrMap it = m_bstMap.begin();
     wdBst tree;
     WindData wd;
     Date d;
     bool found = false;
     float sum = 0;
     int counter = 0;
     while(it != m_bstMap.end()) //iterate through every map element
     {
         tree = it->second;
         tree.GetRootElement(wd);
         wd.GetDate(d);
         if(d.GetMonth() == month) //find tree with matching month
         {
             found = true;
             tree.InorderTraversal(GetAirTempSum,sum);
             counter += tree.TreeNodeCount();
         }
         ++it;
     }
     if(found)
     {
         sum = sum / (float)counter;
         return sum;
     }
     else
     {
         return 0;
     }
 }
References GetAirTempSum(), WindData::GetDate(), Date::GetMonth(), Bst< T >::GetRootElement(), Bst< T >::InorderTraversal(), m_bstMap, and Bst< T >::TreeNodeCount().
Referenced by CalculatesPCCS_T(), and CalculatesPCCT_R().
GetsPCCSolarRadMean()
float WindDataStore::GetsPCCSolarRadMean (int month) private
Method to get the mean of solar rad in every for a specified month.
Parameters
month - Month to be calculated
Returns
mean - Mean of solar rad
Definition at line 412 of file WindDataStore.cpp.
 {
     itrMap it = m_bstMap.begin();
     wdBst tree;
     WindData wd;
     Date d;
     bool found = false;
     int sum = 0;
     int counter = 0;
     while(it != m_bstMap.end()) //iterate through every map element
     {
         tree = it->second;
         tree.GetRootElement(wd);
         wd.GetDate(d);
         if(d.GetMonth() == month) //find tree with matching month
         {
             found = true;
             tree.InorderTraversal(GetSolarRadSum,sum);
             counter += tree.TreeNodeCount();
         }
         ++it;
     }
     if(found)
     {
         sum = sum / (float)counter;
         return sum;
     }
     else
     {
         return 0;
     }
 }
References WindData::GetDate(), Date::GetMonth(), Bst< T >::GetRootElement(), GetSolarRadSum(), Bst< T >::InorderTraversal(), m_bstMap, and Bst< T >::TreeNodeCount().
Referenced by CalculatesPCCS_R(), and CalculatesPCCT_R().
GetsPCCWindSpeedMean()
float WindDataStore::GetsPCCWindSpeedMean (int month) private
Method to get the mean of wind speed in every for a specified month.
Parameters
month - Month to be calculated
Returns
mean - Mean of wind speed
Definition at line 340 of file WindDataStore.cpp.
 {
     itrMap it = m_bstMap.begin();
     wdBst tree;
     WindData wd;
     Date d;
     bool found = false;
     float sum = 0;
     int counter = 0;
     while(it != m_bstMap.end()) //iterate through every map element
     {
         tree = it->second;
         tree.GetRootElement(wd);
         wd.GetDate(d);
         if(d.GetMonth() == month) //find tree with matching month
         {
             found = true;
             tree.InorderTraversal(GetWindSpeedSum,sum);
             counter += tree.TreeNodeCount();
         }
         ++it;
     }
     if(found)
     {
         sum = sum / (float)counter;
         return sum;
     }
     else
     {
         return 0;
     }
 }
References WindData::GetDate(), Date::GetMonth(), Bst< T >::GetRootElement(), GetWindSpeedSum(), Bst< T >::InorderTraversal(), m_bstMap, and Bst< T >::TreeNodeCount().
Referenced by CalculatesPCCS_R(), and CalculatesPCCS_T().
GetWindSpeedSum()
void WindDataStore::GetWindSpeedSum (WindData & wd, float & sum) static private
Method used to get sum of wind speed. To be passed into BST InorderTraversal through function passing
Parameters
wd - WindData object, will be passed in by BST InorderTraversal method
sum - Container for sum of wind speed calculated.
Definition at line 205 of file WindDataStore.cpp.
 {
     sum += wd.GetSpeed();
 }
References WindData::GetSpeed().
Referenced by CalculateWindSpeedMean(), and GetsPCCWindSpeedMean().
GetWindSpeedVector()
void WindDataStore::GetWindSpeedVector (WindData & wd, vector< float > & wsv) static private
Method used to get wind speed from BST, stored into a vector<float>. To be passed into BST InorderTraversal through function passing
Parameters
wd - WindData object, will be passed in by BST InorderTraversal method
wsv - Container for wind speed objects to be stored
Definition at line 244 of file WindDataStore.cpp.
 {
     wsv.push_back(wd.GetSpeed());
 }
References WindData::GetSpeed().
Referenced by CalculatesPCCS_R(), CalculatesPCCS_T(), and CalculateWindSpeedSD().
ReadInputFileToStorage()
bool WindDataStore::ReadInputFileToStorage (const string & fileName)
This method is used to read a csv file and extract the required information within. This method is to be used with the appropriate data type storage methods.
Parameters
fileName - Name of data file
Returns
boolean - Return true if operation is successful, otherwise false.
Definition at line 29 of file WindDataStore.cpp.
 {
     ifstream infile(fileName);
     if( !infile ) return false;
     string line;
     getline(infile,line); // get header column names
     SetHeaderNames(line);
     while(getline(infile,line))
     {
         WindData wd;
         istringstream iss(line); // initialize row into stream format to be used for processing data into individual columns
         string ssline;
         int currentColumn = 0; // first column starts at 0
         while(getline(iss,ssline,','))
         {
             // runs through every storage column, when matching column found, store data into right storage
             StoreDateAndTime(wd,ssline,currentColumn, fileName);
             StoreAirTemp(wd,ssline,currentColumn, fileName);
             StoreSpeed(wd,ssline,currentColumn, fileName);
             StoreSolarRad(wd,ssline,currentColumn, fileName);
             currentColumn++;
         }
         StoreIntoMap(wd);
     }
     infile.close();
     return true;
 }
References SetHeaderNames(), StoreAirTemp(), StoreDateAndTime(), StoreIntoMap(), StoreSolarRad(), and StoreSpeed().
Referenced by StoreDataToSystem(), and Test01().
SetHeaderNames()
void WindDataStore::SetHeaderNames (string & line) private
Method used to set the headers names into the m_headerNames.
Parameters
line - Header name to be stored
Definition at line 86 of file WindDataStore.cpp.
 {
     istringstream iss(line);
     while(getline(iss,line,','))
     {
         m_headerNames.push_back(line);
     }
 }
References m_headerNames.
Referenced by ReadInputFileToStorage().
Size()
int WindDataStore::Size ()
This method is used to find the number of elements in storage.
Returns
size - Number of elements in storage
Definition at line 5 of file WindDataStore.cpp.
 {
     itrMap it = m_bstMap.begin();
     int counter;
     while(it != m_bstMap.end())
     {
         wdBst tree;
         tree = it->second;
         counter += tree.TreeNodeCount();
         ++it;
     }
     return counter;
 }
References m_bstMap, and Bst< T >::TreeNodeCount().
StoreAirTemp()
void WindDataStore::StoreAirTemp (WindData & wd, string & line, int currentColumn, const string & fileName) private
This method is used to store the air temperature into the WindData object
Parameters
wd - WindData object to store at
line - String of data to store
currentColumn - Used to indicate the current data in line
fileName - The file name being read for data extraction. Used for error checking.
Definition at line 121 of file WindDataStore.cpp.
 {
     string name = m_headerNames.at(currentColumn);
     if(name.compare("T") == 0)
     {
         try //catch dirty data
         {
             wd.SetAirTemp(stof(line));
         }
         catch(invalid_argument& e)
         {
             //commented out to avoid cluttering terminal, uncomment if necessary
             //display filename and error caught
             //cout << "Error found at T = " << line << " , Location: " << fileName << endl;
         }
     }
 }
References m_headerNames, and WindData::SetAirTemp().
Referenced by ReadInputFileToStorage().
StoreDateAndTime()
void WindDataStore::StoreDateAndTime (WindData & wd, string & line, int currentColumn, const string & fileName) private
This method is used to store the date and time into the WindData object
Parameters
wd - WindData object to store at
line - String of data to store
currentColumn - Used to indicate the current data in line
fileName - The file name being read for data extraction. Used for error checking.
Definition at line 95 of file WindDataStore.cpp.
 {
     string name = m_headerNames.at(currentColumn);
     if(name.compare("WAST") == 0)
     {
         Date d;
         Time t;
         istringstream iss(line);
         try //catch dirty data
         {
             iss >> d >> t;
             wd.SetDate(d);
             wd.SetTime(t);
         }
         catch(invalid_argument& e)
         {
             //commented out to avoid cluttering terminal, uncomment if necessary
             //display filename and error caught
             //cout << "Error found at WAST = " << line << " , Location: " << fileName << endl;
         }
     }
 }
References m_headerNames, WindData::SetDate(), and WindData::SetTime().
Referenced by ReadInputFileToStorage().
StoreIntoMap()
void WindDataStore::StoreIntoMap (WindData wd) private
Method to store the WindData into storage, first into BSTs, then into the map
Parameters
wd - WindData object to be stored
Definition at line 61 of file WindDataStore.cpp.
 {
     Date d;
     wd.GetDate(d);
     //use iterator to check if key exist in map
     itrMap it = m_bstMap.find(d.GetMonthString()+to_string(d.GetYear()));
     //if key exist, extract wdBst, insert, and reinsert back into map
     if(it != m_bstMap.end())
     {
         wdBst tree;
         tree = it->second;
         tree.Insert(wd);
         m_bstMap[d.GetMonthString()+to_string(d.GetYear())] = tree;
     }
     //else, create new map allocation
     else
     {
         wdBst tree;
         tree.Insert(wd);
         m_bstMap[d.GetMonthString()+to_string(d.GetYear())] = tree;
     }
 }
References WindData::GetDate(), Date::GetMonthString(), Date::GetYear(), Bst< T >::Insert(), and m_bstMap.
Referenced by ReadInputFileToStorage().
StoreSolarRad()
void WindDataStore::StoreSolarRad (WindData & wd, string & line, int currentColumn, const string & fileName) private
This method is used to store the solar radiation into the WindData object
Parameters
wd - WindData object to store at
line - String of data to store
currentColumn - Used to indicate the current data in line
fileName - The file name being read for data extraction. Used for error checking.
Definition at line 160 of file WindDataStore.cpp.
 {
     string name = m_headerNames.at(currentColumn);
     if(name.compare("SR") == 0)
     {
         try //catch dirty data
         {
             wd.SetSolarRad(stoi(line));
         }
         catch(invalid_argument& e)
         {
             //commented out to avoid cluttering terminal, uncomment if necessary
             //display filename and error caught
             //cout << "Error found at S = " << line << " , Location: " << fileName << endl;
         }
     }
 }
References m_headerNames, and WindData::SetSolarRad().
Referenced by ReadInputFileToStorage().
StoreSpeed()
void WindDataStore::StoreSpeed (WindData & wd, string & line, int currentColumn, const string & fileName) private
This method is used to store the wind speed into the WindData object
Parameters
wd - WindData object to store at
line - String of data to store
currentColumn - Used to indicate the current data in line
fileName - The file name being read for data extraction. Used for error checking.
Definition at line 140 of file WindDataStore.cpp.
 {
     string name = m_headerNames.at(currentColumn);
     if(name.compare("S") == 0)
     {
         try //catch dirty data
         {
             wd.SetSpeed(stof(line));
         }
         catch(invalid_argument& e)
         {
             //commented out to avoid cluttering terminal, uncomment if necessary
             //display filename and error caught
             //cout << "Error found at S = " << line << " , Location: " << fileName << endl;
         }
     }
 }
References m_headerNames, and WindData::SetSpeed().
Referenced by ReadInputFileToStorage().
Member Data Documentation
m_bstMap
bstMap WindDataStore::m_bstMap private
Map storing the BSTs, which in turn stores the data
Definition at line 52 of file WindDataStore.h.
Referenced by CalculateAirTempMean(), CalculateAirTempSD(), CalculateSolarRadTotal(), CalculatesPCCS_R(), CalculatesPCCS_T(), CalculatesPCCT_R(), CalculateWindSpeedMean(), CalculateWindSpeedSD(), GetMap(), GetsPCCAirTempMean(), GetsPCCSolarRadMean(), GetsPCCWindSpeedMean(), Size(), and StoreIntoMap().
m_headerNames
vector<string> WindDataStore::m_headerNames private
Vector of header names, used for indicating the csv data retrieved by its columns. To be used for storage of data into appropriate WindData attributes.
Definition at line 58 of file WindDataStore.h.
Referenced by SetHeaderNames(), StoreAirTemp(), StoreDateAndTime(), StoreSolarRad(), and StoreSpeed().
The documentation for this class was generated from the following files:
WindDataStore.h
WindDataStore.cpp